### ISSUE TITLE
Dockeri konteiner

### ISSUE THREAD

**Issue by Renkas** [open-eid/SiGa#1]
Kas on mingi põhjus miks see lahendus ei ole saadaval Dockeri konteinerina, et arendajad saaksid selle kerge vaevaga oma stacki lisada? Või pole lihtsalt asjani jõutud?

Oleks ehk lähiajal võimalik SiGa Dockeri konteinerina publishida?

**Comment by naare** [comment]
Praeguse seisuga ei plaani me SiGa Dockeri imagena publitseerida.

Võime kaaluda dockerfaili publitseerimist lihtsustamaks teenusega liidestumist, kuid soovitame siiski liituda RIA Demo teenusega. Demo teenuse kasutamine on soovituslik seetõttu, et pakutav SiGa teenus ei pruugi pakkuda täit funktsionaalsust mida tarkvara võimaldab.  Demo teenusega liitumiseks kirjutage help@ria.ee.

**Comment by naare** [comment]
Lisasime dockerfaili loomise backlogi, eeldatavasti on tehtud detsembriks.

**Comment by hillar** [comment]
kas detsemeber 2019 või mõni järgnev ?

**Comment by naare** [comment]
Develop harus on dockeri näidis olemas.
