### ISSUE TITLE
Incorrect messageToDisplay length for SmartId

### ISSUE THREAD

**Issue by aasaru** [open-eid/SiGa#10]
Documentation has identical description for messageToDisplay for both SmartID and MobileID. It says:

_Text displayed in addition to ServiceName and before asking signing PIN. Maximum length is 40 bytes. In case of Latin letters, this means also a 40 character long text, but Cyrillic characters may be encoded by two bytes and you will not be able to send more than 20 symbols._

===
In reality Smart-ID uses UTF-8 for this text and every Smart-ID app is capable of displaying up to 60 characters (no matter Cyryllic or not).

**Comment by naare** [comment]
The documentation has been updated.
