### ISSUE TITLE
SmartID testing

### ISSUE THREAD

**Issue by Konservin** [open-eid/SiGa#14]
Are there currently problems with Smart-ID test environment? Authentication and signing seem to be not working in https://sid.demo.sk.ee/portal/login and https://tara-test.ria.ee/ neither for real or test users (https://github.com/SK-EID/smart-id-documentation/wiki/Environment-technical-parameters#test-accounts-for-automated-testing)

**Comment by aarmam** [comment]
Yes Smart-ID test environment is currently unavailable!
https://github.com/SK-EID/smart-id-documentation/wiki/Environment-technical-parameters#test-accounts-for-automated-testing
"Automatic numbers are not working currently."

**Comment by Konservin** [comment]
Is there any approximate time it shall be available again?

**Comment by Konservin** [comment]
Doesn't seem to be working. https://sid.demo.sk.ee/portal/login doesn't send notifications to device and ends up with "Login failed".
I also re-uploaded my cert at https://demo.sk.ee/upload_cert/index.php

**Comment by aarmam** [comment]
It seems [**new** automatic test accounts](https://github.com/SK-EID/smart-id-documentation/wiki/Environment-technical-parameters#test-accounts-for-automated-testing) are now restored! Please try again!

**Comment by Konservin** [comment]
https://support.dokobit.com/article/667-mobile-id-and-smart-id-test-data
This bit still seems to be not working:
![image](https://user-images.githubusercontent.com/5410710/205636457-b0242bbc-c3ae-424d-a82f-cbca1d24bf2b.png)
