### ISSUE TITLE
SmartID signing error: 'Signature encoding error'

### ISSUE THREAD

**Issue by andrese02** [open-eid/SiGa#15]
SmartID signing process is ended with an error after the correct signing PIN is inputted (Device displays a success message).

Extract from log:
`Determining signing certificate from certificate candidates list failed: [Best candidate validation failed : org.apache.xml.security.signature.XMLSignatureException: Signature encoding error\nOriginal Exception was java.security.SignatureException: Signature encoding error]`

Tested with 2 different SmartId demo accounts. One generated long time ago and one generated just prior to testing. Both accounts are using different Android versions.
Signing works in dokobit demo portal for both accounts, so i am assuming this has to be something related to SiGa

SiGa version 2.5.5
Running in Docker
SmartID demo environment
SmartID signatures confirmed by Estonian ID-card

Full log snippet from (assuming) the last 'signing status' call:
[20221130_siga_log.log](https://github.com/open-eid/SiGa/files/10125299/20221130_siga_log.log)

**Comment by heititobi** [comment]
Hello,

As I was unable to reproduce the error, please try deleting all old SmartID accounts and retry signing with new demo account. 
In the end of november Smart-ID Demo service was down and after that the instructions were:
1. Remove "Smart-ID Demo" application from the phone.
2. Reinstall "Smart-ID Demo" application. 
3. Create new "Smart-ID Demo" account.

Also some demo accounts changed -  https://github.com/SK-EID/smart-id-documentation/wiki/Environment-technical-parameters#test-accounts-for-automated-testing.

Please let me know if signing with reinstalled app and new account works or is the error the same.

**Comment by andrese02** [comment]
Unfortunately this didn't help.
Did the following:
* Removed (deleted) all demo accounts from the portal
* deleted all data in Android app
* Uninstalled Android app
* Reinstalled app
* Generated new account
* Validated the account and cert with Estonian ID-card (ESTEID2018)
* Retried signing process

The error is the same. Attached the full log of activites, starting from container start.
[20221207_siga_log02.log](https://github.com/open-eid/SiGa/files/10179126/20221207_siga_log02.log)

**Comment by andrese02** [comment]
None of the demo numbers work. They give back exactly the same response (Encoding error).

**Comment by andrese02** [comment]
I can currently confirm that version 2.6.0 running in docker (see #18) doesn't seem to have this issue for demo numbers.
For some reason i am unable to create a new demo account to test with it. If and when the smartid helpdesk responds, i can retest it with an account. 
Hopefully this bug is fixed in new version.

**Comment by andrese02** [comment]
I can confirm that a freshly registered SmartID demo account (android device, confirmed by estonian ID card) can be used to sign, using SiGa 2.6.0 running in docker (After the signing cert is uploaded to demo.sk.ee).

Therefore is believe this is not reproducable at this time
