### ISSUE TITLE
Docker Setup Failing on build-image, illegal character error

### ISSUE THREAD

**Issue by bigscaryduck** [open-eid/SiGa#20]
Trying to setup the app on Docker and following the instructions. After running:

`./mvnw clean install`

I try the next step of:

`./mvnw spring-boot:build-image -pl siga-webapp -DskipTests`

This fails with this error:

`[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:3.2.5:build-image (default-cli) on project siga-webapp: Execution default-cli of goal org.springframework.boot:spring-boot-maven-plugin:3.2.5:build-image failed: Illegal char <:> at index 5: npipe:////./pipe/dockerDesktopLinuxEngine -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:3.2.5:build-image (default-cli) on project siga-webapp: Execution default-cli of goal org.springframework.boot:spring-boot-maven-plugin:3.2.5:build-image failed: Illegal char <:> at index 5: npipe:////./pipe/dockerDesktopLinuxEngine
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)`

Java version: 17.0.10

Docker Version:  Docker Desktop 4.31.1 (153621)

Thanks for any tips in advanced!

**Comment by Sedemicra** [comment]
Hello!
Thank you for your issue report.

Based on the current information, it appears to be an issue between Spring Boot and latest Docker Desktop version. I have created an [issue to Spring Boot github](https://github.com/spring-projects/spring-boot/issues/41199) for further clarification.

In the meanwhile, the recommended solution is to downgrade Docker Desktop to version 4.30.0.
You can download this specific version from [Docker Desktop release notes](https://docs.docker.com/desktop/release-notes/).
To bypass the version check during installation, you can run the installer with the following command: `.\Docker Desktop Installer.exe install --disable-version-check`

**Comment by bigscaryduck** [comment]
Thanks! Will try to downgrade and will keep an eye on the Spring Boot issue you created.
