### ISSUE TITLE
Repeatability of the signature creation process example

### ISSUE THREAD

**Issue by thsnr** [open-eid/SiGa#3]
### Summary

I am trying to repeat the signature creation process example at [Authorization](https://github.com/open-eid/SiGa/wiki/Authorization). The signature value I get does not match the example value.

I am guessing that the difference comes from whitespacing in the request body. I tried a few variations (tabs vs spaces, linux vs windows linefeeds, no whitespace at all, etc), but was unable to get the exact signature value.

The example could be more specific about what the exact byte content of the request body is.

### Steps to Reproduce

Calculate the HMAC-SHA256 signature of

```
a7fd7728-a3ea-4975-bfab-f240a67e894f:1580221745:POST:/hashcodecontainers:{
    "dataFiles": [
        {
            "fileName": "test.txt",
            "fileHashSha512": "hQVz9wirVZNvP/q3HoaW8nu0FfvrGkZinhADKE4Y4j/dUuGfgONfR4VYdu0p/dj/yGH0qlE0FGsmUB2N3oLuhA==",
            "fileSize": 189,
            "fileHashSha256": "RnKZobNWVy8u92sDL4S2j1BUzMT5qTgt6hm90TfAGRo="
        }
    ]
}
```

using the key `746573745365637265744b6579303031`.

Hexadecimal version of the plaintext for reference:

```
61376664373732382d613365612d343937352d626661622d663234306136
3765383934663a313538303232313734353a504f53543a2f68617368636f
6465636f6e7461696e6572733a7b0a20202020226461746146696c657322
3a205b0a20202020202020207b0a2020202020202020202020202266696c
654e616d65223a2022746573742e747874222c0a20202020202020202020
20202266696c6548617368536861353132223a20226851567a3977697256
5a4e76502f7133486f6157386e753046667672476b5a696e6841444b4534
59346a2f6455754766674f4e6652345659647530702f646a2f7947483071
6c45304647736d5542324e336f4c7568413d3d222c0a2020202020202020
202020202266696c6553697a65223a203138392c0a202020202020202020
2020202266696c6548617368536861323536223a2022526e4b5a6f624e57
56793875393273444c3453326a3142557a4d54357154677436686d393054
664147526f3d220a20202020202020207d0a202020205d0a7d
```

Note that the wiki example lists the plaintext as

```
plaintext = "13d03497-67bf-4879-8382-e8072ea04a09" + ":" + "1551102625" + ":" + "POST" + ":" + "/hashcodecontainers?someParam=value%20with%20space" + ":" + requestBody("UTF-8")
```

which is incorrect and was probably not updated when the rest of the example was.

### Expected Results

`e770c25b830ca28b8a80f00257ddcab9e7ab2dc9b647f2b36737f07e9db36f8b`

### Actual Results

`e1680b3ee883b8afb87b77802dde2f94eed7e0d8b5e02cf10cde41bdb332ccfb`

**Comment by naare** [comment]
The example plaintext was not indeed updated. I have now updated the example and replaced the pseudo code with exact string used to calculate the signature. Hopefully this helps.

**Comment by thsnr** [comment]
Yes, with the updates values, I was now able to successfully replicate the signature. Thank you.
