### ISSUE TITLE
OCSP failure (hashcode API with smartcard) returns error 500

### ISSUE THREAD

**Issue by plaes** [open-eid/SiGa#6]
Currently, RIA dsig demo API returns error 500 when certificate fails OCSP check during finalize phase.
IMHO, this is a bit harsh and should be actually 400 level error.

**Comment by naare** [comment]
Improvent of error handling in signature finalization has been added to backlog.

**Comment by naare** [comment]
This has been improved in 2.4.0 release: https://github.com/open-eid/SiGa/releases/tag/v2.4.0
