### ISSUE TITLE
Smartcard signature finalization error is too generic

### ISSUE THREAD

**Issue by plaes** [open-eid/SiGa#7]
Current signature finalization error for PUT `/hashcodecontainers/{container_id}/remotesigning/{signature_id}` for smartcards is too generic and tells what happened, but instead should tell why it happened:
```
STATUS 400: {"errorCode":"SIGNATURE_CREATION_EXCEPTION","errorMessage":"Unable to finalize signature"}
```

We have occasional users (~1 in 20) who run into this failure during the finalization phase (even multiple times in a row) for no apparent reason (certificate is valid).

**Comment by naare** [comment]
We have added a ticket based your previous request: https://github.com/open-eid/SiGa/issues/6  We will look into how to improve the error handling on signature finalization.

**Comment by naare** [comment]
This has been improved in 2.4.0 release: https://github.com/open-eid/SiGa/releases/tag/v2.4.0
