### ISSUE TITLE
How to create siga_service entries?

### ISSUE THREAD

**Issue by Renkas** [open-eid/SiGa#8]
Shouldn't SiGa have some kind of API to add new services to `siga_service` table?
How is it supposed to be managed?

I could do it all "manually" but there's a problem with generating `signing_secret` that I have not figured out.

I tried generating the secret myself with an online tool: https://8gwifi.org/pbe.jsp
I used same defaults as SiGa has:
Password: `encryptorKey`
Rounds: `1000` (seems to be default value that is also used in SiGa)
Cipher: `PBEWITHSHA-256AND256BITAES-CBC-BC` (same as set in `siga.security.jasypt.encryption-algo`)

Problem is that when inserting generated string to DB I'm unable to use said client. At the same time SiGa test data is working fine. For example:
secret: `746573745365637265744b6579303031`
uuid: `a7fd7728-a3ea-4975-bfab-f240a67e894f`

I also tried the same tool to decrypt signing_secret from dev data.
`zXTTdPFdntdwMsN8LCBXw4Eb+BnD/YPU87mWvpOaQwp6PrFNKQZ21fP1CPY/zITFQE0BANHIP7VwRwAsa+657Q==`
And it's not working. I really don't seem to be able to figure it out currently.

Any pointers? Or maybe any plans to add some API to manage services?

PS! I'm not Java developer so maybe I have missed something obvious.

**Comment by naare** [comment]
Hello,

Currently there is no plans for providing API interface for client registration/management. You need to insert the values manually into the database or build your own specific "admin interface".

Regarding the client registration problem you can try out http://www.jasypt.org/cli.html

Before using Jasypt CLI put Bouncy Castle Provider version 1.61+ library to Jasypt CLI lib folder.

`
$ jasypt-1.9.2 bin/encrypt.sh providerClassName="org.bouncycastle.jce.provider.BouncyCastleProvider" algorithm=PBEWITHSHA-256AND256BITAES-CBC-BC input="YourSecretToEncrypt" password=encryptorKey
`

Hope this helps.

**Comment by sandy-bridge** [comment]
@Renkas were you able to generate/decrypt secrets? I followed naare's instructions and still couldn't decrypt the secrets from dev-data.yaml.

**Comment by Renkas** [comment]
Me genereerime secreteid niimoodi:
> docker run --rm -e ALGORITHM="PBEWithMD5AndDES" -e MASTER_KEY="encryptorKey" -e INPUT_PASSWORD="RANDOM_32CHAR_STRING" dperezcabrera/jasypt-encrypt-cli
